
# Build stage
FROM oven/bun:1 AS builder

WORKDIR /usr/src/app

# Install Nest.js CLI globally
RUN bun add -g @nestjs/cli

COPY package*.json bun.lock ./
RUN bun install # Install both production and development dependencies

COPY . .

RUN bun run build
# Production image
FROM oven/bun:1

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/bun.lock ./
COPY --from=builder /usr/src/app/dist ./dist

# Prune development dependencies
RUN bun install --production
CMD ["bun", "dist/main"]
