
# Build stage
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

# Install Nest.js CLI globally
RUN npm i -g @nestjs/cli

COPY package*.json package-lock.json ./
RUN npm install # Install both production and development dependencies

COPY . .

RUN npm run build

# Production image
FROM node:20-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/package-lock.json ./
COPY --from=builder /usr/src/app/dist ./dist

# Prune development dependencies
RUN npm install --production

CMD ["node", "dist/main"]
