# Use the official Bun image as the base
# See all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 AS base

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and bun.lockb, then install dependencies
# This leverages Docker's build cache for faster subsequent builds
COPY package.json bun.lock ./
RUN bun install

RUN bun run build


# Copy the rest of the application source code
COPY . .


# Expose the port your app runs on (e.g., 3000)
EXPOSE 3000/tcp



# Command to run your application using Bun
# Replace "index.ts" with your application's entry file or a script name from package.json
CMD ["bun", ".next/standalone/server.js"]
